export enum AppMessageCode {
  UserNotFound = 'USER_NOT_FOUND',
  LoginInvalid = 'LOGIN_INVALID',
  LoginSuccess = 'LOGIN_SUCCESS',
  RequiredFields = 'REQUIRED_FIELDS',
  UnexpectedError = 'UNEXPECTED_ERROR',
  NetworkError = 'NETWORK_ERROR',
  AnimalCreated = 'ANIMAL_CREATED',
  FarmRequired = 'FARM-REQUIRED',
  DiffPaddock = 'DIFF_PADDOCK',
  VaccinationCreated = 'VACCINATION-CREATED',
  VaccinationCreateError = 'VACCINATION-CREATED-ERROR',
  AnimalsRequired = 'ANIMALS-REQUIRED',
  BirthCreated = 'BIRTH-CREATED',
  BirthCreateError = 'BIRTH-CREATE-ERROR',
  FarmCreated = 'FARM-CREATED',
  FarmCreateError = 'FARM-CREATE-ERROR',
}
